### ISSUE TITLE
ESLint Error: Cannot find module

### ISSUE THREAD

**Issue by Abourass** [getify/eslint-plugin-proper-ternary#5]
Hello! Sorry maybe I'm doing something wrong here, but when I added this plugin:

`npm i @getify/eslint-plugin-proper-ternary --save-dev`

Then added as suggested:

```
"eslintConfig": {
    "plugins": [
      "security"
    ],
    "extends": [
      "airbnb-base",
      "plugin:node/recommended",
      "plugin:security/recommended",
      "@getify/proper-ternary"
    ],
    "env": {
      "shared-node-browser": true,
      "node": true,
      "es6": true,
      "mongo": true,
      "jquery": true,
      "jest": true
    },
    "rules": {
      "@getify/proper-ternary/nested": "error",
      "@getify/proper-ternary/parens": "error",
		......
```

WebStorm keeps telling me: 
`ESLint: Error: Cannot find module '@getify/eslint-config-proper-ternary`

I double checked my package-lock:

```
    "@getify/eslint-plugin-proper-ternary": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/@getify/eslint-plugin-proper-ternary/-/eslint-plugin-proper-ternary-1.0.2.tgz",
      "integrity": "sha512-2fhh28lSdZ5A4gOl6S1bgH2BEpEwBDmxe13v3Uo+CXNmgZcd7qbdbZ6V05OaawjsLVPNvDcQivNEGbHnmdHuqg==",
      "dev": true
    },
```

So not sure what I'm doing wrong here

**Comment by getify** [comment]
You have to list it in the "plugins" (not "extends") section of the eslint config to load the plugin: "@getify/proper-ternary".

https://github.com/getify/eslint-plugin-proper-ternary/blob/master/README.md#enabling-the-plugin

**Comment by Abourass** [comment]
Oh jeese. I'm sorry about that.  Thank you so much!

**Comment by getify** [comment]
FYI: I do plan on adding one or more config presets to the plugin to make getting started easier. Then you'll be able to *also* add it to the "extends" to get base rule configurations to start from.
